### ISSUE TITLE
The virus is there.

### ISSUE THREAD

**Issue by boot4root** [mediafactory/yats#10]
![screen](https://user-images.githubusercontent.com/85632791/146915290-8da064b3-2fc4-41b8-82b2-e2695aecbdde.jpg)

Could you explain, why the code contains virus?

thanks

**Comment by Henner** [comment]
it is for testing purpose! The following file contains the ICAR Test virus:
https://github.com/mediafactory/yats/blob/master/test/icar.txt

see https://en.wikipedia.org/wiki/EICAR_test_file for more info

**Comment by boot4root** [comment]
Thank You for the rapid response!
