### ISSUE TITLE
How to configure and deploy this project?

### ISSUE THREAD

**Issue by pandya2368** [mediafactory/yats#5]
Hey! Anyone please help to configure and demo this code?(if possible step by step)
coz  I am new to work with Django and this project can help me to understand and learn something new.
which IDE i need to use ? (generally I am used Spyder IDE for python programm)

**Comment by Henner** [comment]
Hi,
it is easy as stated in the readme.
Install Vagrant
https://www.vagrantup.com

Install VirtualBox:
https://www.virtualbox.org

Checkout this project.
Open a shell und cd into the vagrant folder
type: vagrant up

wait...

Point your browser at:  http://192.168.33.11 
(or change the settings in the Vagrant file)

You can use any editor to change the python files. They will be changed in the virtual box as well.
For deploying this project, check out the django docu here: 
https://docs.djangoproject.com/en/1.7/howto/deployment/
