### ISSUE TITLE
Documentation on how it was put together and how to set up a local instance.

### ISSUE THREAD

**Issue by timoc** [mediafactory/yats#6]
I would to be able to use some of the yats alongside some other django apps, but it is very difficult to get an idea about how this was put together, and how to setup a local (non vagrant) setup, such as a container. 
Is there documentation available that can be checked in about setting up local development. configuring the various requirements etc?

**Comment by Henner** [comment]
Look into the Vagrant folder into bootstrap.sh 
There is all you need for debian. Should also work on ubuntu - maybe package names differ.

**Comment by pauloscardine** [comment]
I just deployed an instance, pretty much just patched bootstrap.sh and web.ini with the paths I wanted. The only glitch was having to remove `sudo` from the command unzipping the xapian tarballs (the buid step failed because the folder was owned by root).

**Comment by Henner** [comment]
OK. So did it work for you or do you need further help?

**Comment by pauloscardine** [comment]
Worked for me, I just wanted to comment here in order to help someone trying to do the same. I will repeat the process soon, if you think it is a good idea I can document the steps and send a PR.

**Comment by RomMarwa** [comment]
Yes Please, I need help how to run it on local.

**Comment by swamybachu** [comment]
Hello, i need help running it locally. I am using Anaconda, and have a environment in it.

**Comment by Henner** [comment]
Sorry, I am not familiar with Anaconda.

You need all python modules in the modules folder and all from requirements.txt
YATS is a Python 2.x Django 1.11 Project. For more info on Django see: https://www.djangoproject.com
So you need the web folder in sites:
cd into that and do: python manage.py check

read bootstrap.sh and see, what is done for installation.

And you need a xapian installation. You can use other search engines - see http://haystacksearch.org for more info. You can even disable haystack in settings.py under INSTALLED_APPS.

if it all does not work, git vagrant a try ;-)
https://www.vagrantup.com

**Comment by swamybachu** [comment]
Thank you for the response @Henner . 
I see that this is a Python 2x app. 
Do you have any plans to upgrade it to make it Python 3x compatible.

**Comment by Henner** [comment]
yes, as this is an active project, we have to until the end of this year ;-)

**Comment by akshatrathore** [comment]
can anyone help me with the steps to run this project locally on ubuntu

**Comment by Henner** [comment]
the easiest way is: 
- install vagrant
- install virtualBox
- checkout this project
- cd into the vagrant folder
- on a shell type: vagrant up

**Comment by akshatrathore** [comment]
I need to check the demo site for my reference, but the site is down from couple of weeks.

**Comment by Henner** [comment]
what site is down? Our demo here? 
https://yats.mediafactory.de/
I can open it and we are getting lots of test tickets by others...

**Comment by akshatrathore** [comment]
ok thanks sir.
