### ISSUE TITLE
Error while creating a ticket via a document

### ISSUE THREAD

**Issue by korzeczl** [mediafactory/yats#7]
Version: demo 12/06/2019

In order to reproduce the error:

- Create a document
- Click on the button 'create ticket'

The ticket is actually created but an error pops up.

Html: [UnicodeDecodeError at _docs_ticket_20_.zip](https://github.com/mediafactory/yats/files/3281352/UnicodeDecodeError.at._docs_ticket_20_.zip)

**Comment by Hinnack** [comment]
Thank you, for reporting this.
The reference was messy and missing. It is fixed now!
