### ISSUE TITLE
Login on Demo doesn't work

### ISSUE THREAD

**Issue by sam9032** [mediafactory/yats#9]
Hi there,
the demo login doesn't work. It says "Data invalid".

**Comment by farzbood** [comment]
Seems So!

**Comment by Henner** [comment]
sorry, some fancy user changed the passwords...

**Comment by sam9032** [comment]
Thank you 😀

**Comment by simplylu** [comment]
I think some clowns did it again for staff.user

**Comment by Henner** [comment]
sorry, yes - and deleted everything :-(
should work again
